version: '2'
services:
    menuweb-app:
        image: menuweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://menuweb-mysql:3306/menuweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    menuweb-mysql:
        extends:
            file: mysql.yml
            service: menuweb-mysql
